version: 2.1
orbs: 
  cypress: cypress-io/cypress@1

workflows: 
  "Run tests, generate report, send to slack":
    jobs: 
      - cypress/install
      - 
        cypress/run: 
          group: "all tests"
          parallel: true
          parallelism: 4
          record: false
          requires: 
            - cypress/install
      - report
          
jobs:
  report:
    docker:
      - image: cypress/base:17.8.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
        - run: npm install
        - run: ./node_modules/.bin/cypress-slack-reporter-full