version: 2.1
orbs: 
  cypress: cypress-io/cypress@1

workflows: 
  version: 2
  "Run tests":
    jobs: 
      - cypress/install
      - 
        cypress/run: 
          context: Build
          post-steps:
            - when: always
            - store_artifacts:
                path: mochawesome-report
            - run: ./node_modules/.bin/cypress-slack-reporter-full
          group: "all tests"
          parallel: false
          #parallelism: 4
          record: false
          requires: 
            - cypress/install
      
  "generate report and send to slack":
    jobs:
      - report


jobs:
  report:
    docker:
      - image: alpine:latest
    steps: 
      - run: ./node_modules/.bin/cypress-slack-reporter-full