version: 2.1
orbs: 
  cypress: cypress-io/cypress@1

workflows: 
  "Run tests, generate report, send to slack":
    jobs: 
      - cypress/install
      - 
        cypress/run: 
          post-steps:
            - store_artifacts:
                path: mochawesome-report
            - run: ./node_modules/.bin/cypress-slack-reporter-full
          group: "all tests"
          parallel: true
          parallelism: 4
          record: false
          requires: 
            - cypress/install
        